### PR TITLE
Added props for custom EventSource and on error method

### PR DESCRIPTION
**Pull request by hasnat**
also `propTypes` and `defaultProps` were not assigned to `EventSourceHOC`

### CODE REVIEW

**Comment by revolunet** [comment]
Hi, thanks for your contribution !

**Comment by revolunet** [comment]
thank you !

**Comment by hasnat** [comment]
will you be releasing it on npm soon?

**Comment by hasnat** [comment]
also, thanks for the merge

**Comment by revolunet** [comment]
Hi !
Ive just pushed @1.1.0 to npm, tell me if ok for you 

I made two changes :
 - rename components to ReactEventSource everywhere
 - upgrade tooling to nwb, much lighter

**Comment by hasnat** [comment]
works perfect, thanks very much.
I like the nwb change.

**Pull request merged**
